// This file is fully generated by running parsergen v1.7.0
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/GLR.h>

class C_SQLParser: public bux::GLR::C_Parser
{
public:

    // Ctor
    C_SQLParser();
};
