// This file is fully generated by running parsergen v1.6.2
// with grammer definition file "grammar.txt"

#ifndef ParserH
#define ParserH

#include <bux/GLR.h>

class C_SQLParser: public bux::GLR::C_Parser
{
public:

    // Ctor
    C_SQLParser();
};

#endif // ParserH
